import type { SiteContent } from './types'

export const en: SiteContent = {
  lang: 'en',
  meta: {
    title: 'Noctara. — Professional Photographer | Clermont-Ferrand',
    description: 'Professional photographer based in Clermont-Ferrand. Portrait, wedding, corporate, events. Every moment has only one chance.',
    locale: 'en_US',
  },
  nav: {
    book: 'Book Now',
    links: [
      { label: 'Portfolio', href: '#portfolio' },
      { label: 'About', href: '#about' },
      { label: 'Pricing', href: '#tarifs' },
      { label: 'Reviews', href: '#temoignages' },
      { label: 'Contact', href: '#contact' },
    ],
  },
  hero: {
    line1: 'EVERY MOMENT',
    line2: 'HAS ONE CHANCE',
    description: 'Professional photographer based in Clermont-Ferrand, immortalizing your most precious moments with a unique artistic vision.',
    cta: 'Explore the portfolio',
    badge: '01 / NOCTARA. — CLERMONT-FERRAND · WORLDWIDE',
  },
  ticker: ['PORTRAIT', 'CORPORATE', 'WEDDING', 'NOCTARA', 'PHOTOGRAPHY', 'EVENTS'],
  stats: [
    { value: '50', suffix: '+', label: 'Happy clients' },
    { value: '200', suffix: '+', label: 'Photoshoots' },
    { value: '48', suffix: 'h', label: 'Response time' },
    { value: '5', suffix: '★', label: 'Average rating' },
  ],
  portfolio: {
    title: 'Portfolio',
    subtitle: 'A curated selection of recent work, between natural light and mastered staging.',
    items: [
      { src: 'https://images.unsplash.com/photo-1531804226768-a0e40b5f5f00', alt: 'Natural light portrait', caption: 'Studio Portrait · 2024', w: 800, h: 1100 },
      { src: 'https://images.unsplash.com/photo-1519741497674-4e2af5b1d1c9', alt: 'Wedding ceremony', caption: 'Wedding · Château de Murol', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1554080353-a576cf803bda', alt: 'Mountain landscape at sunset', caption: 'Landscape · Massif du Sancy', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a', alt: 'Fashion portrait woman', caption: 'Fashion · Winter Collection', w: 800, h: 1200 },
      { src: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4', alt: 'Volcanic mountain', caption: 'Nature · Puy de Dôme', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87', alt: 'Corporate event', caption: 'Corporate · Summit 2024', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1682685797660-3d847763208e', alt: 'Artistic male portrait', caption: 'Portrait · Black Series', w: 800, h: 1067 },
      { src: 'https://images.unsplash.com/photo-1501854140801-50d01698950b', alt: 'Misty forest', caption: 'Nature · Auvergne Forest', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1', alt: 'Business portrait', caption: 'Corporate · Pro Portraits', w: 800, h: 1067 },
    ],
  },
  about: {
    title: 'Behind the lens',
    subtitle: 'One vision. One moment. A lifetime.',
    paragraphs: [
      'Based in Clermont-Ferrand, I capture the essence of moments that truly matter. My approach is both discreet and artistic — I seek natural light, the authenticity of emotions, and the beauty in detail.',
      'Whether for a wedding, corporate shoot, or personal artistic project, I put my eye and experience at the service of your vision. Each image is considered, framed, and delivered with care.',
      'Because every moment only has one chance.',
    ],
    tags: ['Portrait', 'Wedding', 'Corporate', 'Events', 'Fashion', 'Architecture'],
    signature: 'Noctara',
  },
  pricing: {
    title: 'Pricing',
    subtitle: 'Transparent offers, designed to adapt to every project.',
    togglePersonal: 'Personal',
    togglePro: 'Professional',
    ctaPersonal: 'Book this package',
    ctaPro: 'Request a quote',
    personal: [
      {
        name: 'The Essential',
        price: '150',
        unit: '€',
        features: ['1h shooting', '20 retouched photos', 'Private online gallery', 'Delivery within 7 days'],
      },
      {
        name: 'The Essential Plus',
        price: '280',
        unit: '€',
        features: ['3h shooting', '60 retouched photos', 'Private online gallery', '2 outfits', 'Delivery within 5 days'],
        highlight: true,
        badge: 'Popular',
      },
      {
        name: 'Wedding',
        price: '550',
        unit: '€+',
        features: ['Full day', '150+ retouched photos', 'Digital album', 'Preparations included', 'Delivery within 3 weeks'],
      },
    ],
    pro: [
      {
        name: 'Pro Portrait',
        price: 'Quote',
        features: ['Team portraits', 'Studio or outdoor', 'Pro retouch', 'HD delivery', 'Commercial use'],
      },
      {
        name: 'Key Event',
        price: 'Quote',
        features: ['Event coverage', 'Multi-location', 'Fast delivery', 'Extended rights', 'Product shooting'],
        highlight: true,
        badge: 'Custom',
      },
      {
        name: 'The Showcase',
        price: 'Quote',
        features: ['Architecture & interiors', 'Product packshot', 'Art direction', 'Advertising photos', 'Unlimited use'],
      },
    ],
  },
  process: {
    title: 'How does it work?',
    subtitle: 'A simple process, designed to put you at ease at every step.',
    steps: [
      { icon: 'chat', title: 'We talk', description: 'A first exchange to understand your project, your expectations, and find the right angle together.' },
      { icon: 'doc', title: 'The quote', description: 'I send you a clear, detailed proposal with no surprises or hidden costs.' },
      { icon: 'camera', title: 'The shoot', description: 'On the day, I capture your moments with discretion, naturalness, and attention to detail.' },
      { icon: 'gallery', title: 'Delivery', description: 'Your private gallery is available online within the agreed timeframe, ready to download.' },
    ],
  },
  testimonials: {
    title: 'What they say',
    subtitle: 'My clients\' satisfaction is my best recommendation.',
    items: [
      { name: 'Sophie M.', role: 'Bride — Summer 2024', text: 'Absolutely beautiful photos that capture the essence of our day. I\'m moved every time I look at them. Thank you from the bottom of my heart!', initials: 'SM' },
      { name: 'Thomas D.', role: 'Sales Director', text: 'Exceptional quality corporate shoot. Our team is delighted, the photos were used immediately for our website and communication materials.', initials: 'TD' },
      { name: 'Clara B.', role: 'Fashion Blogger', text: 'Exactly what I was looking for my Instagram content. Creative, attentive, and a result that exceeds my expectations. I\'ll definitely come back.', initials: 'CB' },
      { name: 'Marc & Julie', role: 'Couple — 2024', text: 'We were looking for someone discreet who knows how to blend in to capture real moments. That\'s exactly what we got. Thank you so much.', initials: 'MJ' },
      { name: 'Volta Agency', role: 'Art Director', text: 'Professionalism, responsiveness, and a rare artistic sense. A trusted partner for all our visual projects. Highly recommended.', initials: 'AV' },
    ],
  },
  clients: {
    title: 'They trust us',
  },
  contact: {
    title: 'Get in touch',
    subtitle: 'A project? An idea? I\'m listening.',
    address: '15 Rue Blatin',
    city: 'Clermont-Ferrand, France',
    email: 'contact@thenoctara.com',
    availability: 'Availability',
    available: 'Available for new projects',
    form: {
      name: 'Your name',
      email: 'Your email',
      message: 'Your message',
      send: 'Send message',
      sending: 'Sending...',
      success: 'Message sent! I\'ll reply within 48h.',
    },
  },
  devis: {
    title: 'Request a quote',
    subtitle: 'Tell me about your project',
    fields: {
      company: 'Company (optional)',
      name: 'Your name *',
      email: 'Your email *',
      date: 'Desired date',
      location: 'Location / City',
      people: 'Number of people',
      budget: 'Estimated budget',
      message: 'Describe your project *',
      send: 'Send request',
      sending: 'Sending...',
      success: 'Request sent! I\'ll contact you shortly.',
    },
    budgets: ['< €500', '€500 – €1,000', '€1,000 – €2,000', '> €2,000'],
  },
  footer: {
    description: 'Professional photographer based in Clermont-Ferrand. Every moment has only one chance.',
    links: [
      { label: 'Portfolio', href: '#portfolio' },
      { label: 'About', href: '#about' },
      { label: 'Pricing', href: '#tarifs' },
      { label: 'Reviews', href: '#temoignages' },
      { label: 'Contact', href: '#contact' },
    ],
    legal: [
      { label: 'Privacy Policy', href: '/en/privacy' },
      { label: 'Terms', href: '/en/cgv' },
      { label: 'Legal Notice', href: '/en/legal-notice' },
    ],
    copyright: '© 2025 Noctara. All rights reserved.',
  },
}
