import type { SiteContent } from './types'

export const fr: SiteContent = {
  lang: 'fr',
  meta: {
    title: 'Noctara. — Photographe Professionnel | Clermont-Ferrand',
    description: 'Photographe professionnel basé à Clermont-Ferrand. Portrait, mariage, corporate, événement. Chaque instant a une seule chance.',
    locale: 'fr_FR',
  },
  nav: {
    book: 'Réserver',
    links: [
      { label: 'Portfolio', href: '#portfolio' },
      { label: 'À propos', href: '#about' },
      { label: 'Tarifs', href: '#tarifs' },
      { label: 'Avis', href: '#temoignages' },
      { label: 'Contact', href: '#contact' },
    ],
  },
  hero: {
    line1: 'CHAQUE INSTANT',
    line2: 'A UNE SEULE CHANCE',
    description: 'Photographe professionnel basé à Clermont-Ferrand, immortalisant vos moments les plus précieux avec une vision artistique unique.',
    cta: 'Découvrir le portfolio',
    badge: '01 / NOCTARA. — CLERMONT-FERRAND · WORLDWIDE',
  },
  ticker: ['PORTRAIT', 'CORPORATE', 'MARIAGE', 'NOCTARA', 'PHOTOGRAPHIE', 'ÉVÉNEMENT'],
  stats: [
    { value: '50', suffix: '+', label: 'Clients satisfaits' },
    { value: '200', suffix: '+', label: 'Shootings réalisés' },
    { value: '48', suffix: 'h', label: 'Délai de réponse' },
    { value: '5', suffix: '★', label: 'Note moyenne' },
  ],
  portfolio: {
    title: 'Portfolio',
    subtitle: 'Une sélection de travaux récents, entre lumière naturelle et mise en scène maîtrisée.',
    items: [
      { src: 'https://images.unsplash.com/photo-1531804226768-a0e40b5f5f00', alt: 'Portrait en lumière naturelle', caption: 'Portrait Studio · 2024', w: 800, h: 1100 },
      { src: 'https://images.unsplash.com/photo-1519741497674-4e2af5b1d1c9', alt: 'Cérémonie de mariage', caption: 'Mariage · Château de Murol', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1554080353-a576cf803bda', alt: 'Paysage montagne au coucher du soleil', caption: 'Paysage · Massif du Sancy', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a', alt: 'Portrait femme mode', caption: 'Mode · Collection Hiver', w: 800, h: 1200 },
      { src: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4', alt: 'Montagne volcanique', caption: 'Nature · Puy de Dôme', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87', alt: 'Événement corporate', caption: 'Corporate · Summit 2024', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1682685797660-3d847763208e', alt: 'Portrait artistique homme', caption: 'Portrait · Série Noir', w: 800, h: 1067 },
      { src: 'https://images.unsplash.com/photo-1501854140801-50d01698950b', alt: 'Forêt brumeuse', caption: 'Nature · Forêt d\'Auvergne', w: 800, h: 534 },
      { src: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1', alt: 'Portrait business', caption: 'Corporate · Portraits Pro', w: 800, h: 1067 },
    ],
  },
  about: {
    title: 'Derrière l\'objectif',
    subtitle: 'Une vision. Un instant. Une éternité.',
    paragraphs: [
      'Photographe basé à Clermont-Ferrand, je capture l\'essence des moments qui comptent vraiment. Mon approche se veut à la fois discrète et artistique — je cherche la lumière naturelle, l\'authenticité des émotions, et la beauté dans le détail.',
      'Que ce soit pour un mariage, un shooting corporate, ou un projet artistique personnel, je mets mon oeil et mon expérience au service de votre vision. Chaque image est pensée, cadrée, et livrée avec soin.',
      'Parce que chaque instant n\'a qu\'une seule chance.',
    ],
    tags: ['Portrait', 'Mariage', 'Corporate', 'Événement', 'Mode', 'Architecture'],
    signature: 'Noctara',
  },
  pricing: {
    title: 'Tarifs',
    subtitle: 'Des offres transparentes, conçues pour s\'adapter à chaque projet.',
    togglePersonal: 'Particulier',
    togglePro: 'Professionnel',
    ctaPersonal: 'Réserver cette formule',
    ctaPro: 'Demander un devis',
    personal: [
      {
        name: "L'Essentiel",
        price: '150',
        unit: '€',
        features: ['1h de shooting', '20 photos retouchées', 'Galerie privée en ligne', 'Livraison sous 7 jours'],
      },
      {
        name: "L'Essentiel Plus",
        price: '280',
        unit: '€',
        features: ['3h de shooting', '60 photos retouchées', 'Galerie privée en ligne', '2 tenues', 'Livraison sous 5 jours'],
        highlight: true,
        badge: 'Populaire',
      },
      {
        name: 'Mariage',
        price: '550',
        unit: '€+',
        features: ['Journée complète', '150+ photos retouchées', 'Album numérique', 'Préparatifs inclus', 'Livraison sous 3 semaines'],
      },
    ],
    pro: [
      {
        name: 'Portrait Pro',
        price: 'Devis',
        features: ['Portraits équipe', 'Studio ou extérieur', 'Retouche pro', 'Livraison HD', 'Usage commercial'],
      },
      {
        name: "L'Événement Clé",
        price: 'Devis',
        features: ['Couverture événement', 'Multi-lieu', 'Rapidité de livraison', 'Droits étendus', 'Shooting produits'],
        highlight: true,
        badge: 'Sur mesure',
      },
      {
        name: 'La Vitrine',
        price: 'Devis',
        features: ['Architecture & intérieurs', 'Packshot produit', 'Direction artistique', 'Photos pour publicité', 'Usage illimité'],
      },
    ],
  },
  process: {
    title: 'Comment ça se passe ?',
    subtitle: 'Un processus simple, pensé pour vous mettre à l\'aise à chaque étape.',
    steps: [
      { icon: 'chat', title: 'On se parle', description: 'Un premier échange pour comprendre votre projet, vos attentes, et trouver le bon angle ensemble.' },
      { icon: 'doc', title: 'Le devis', description: 'Je vous envoie une proposition claire et détaillée, sans surprise ni coûts cachés.' },
      { icon: 'camera', title: 'Le shooting', description: 'Le jour J, je capture vos moments avec discrétion, naturel, et une attention aux détails.' },
      { icon: 'gallery', title: 'La livraison', description: 'Votre galerie privée est disponible en ligne dans les délais convenus, prête à être téléchargée.' },
    ],
  },
  testimonials: {
    title: 'Ce qu\'ils disent',
    subtitle: 'La satisfaction de mes clients est ma meilleure carte de visite.',
    items: [
      { name: 'Sophie M.', role: 'Mariée — Été 2024', text: 'Des photos absolument magnifiques, qui capturent l\'essence de notre journée. Je suis émue à chaque fois que je les regarde. Merci du fond du cœur !', initials: 'SM' },
      { name: 'Thomas D.', role: 'Directeur Commercial', text: 'Shooting corporate d\'une qualité exceptionnelle. Notre équipe est ravie, les photos ont été utilisées immédiatement pour notre site et nos supports de communication.', initials: 'TD' },
      { name: 'Clara B.', role: 'Blogueuse Mode', text: 'Exactement ce que je cherchais pour mes contenus Instagram. Créatif, à l\'écoute, et un résultat qui dépasse mes attentes. Je reviendrai sans hésiter.', initials: 'CB' },
      { name: 'Marc & Julie', role: 'Couple — PACS 2024', text: 'On cherchait quelqu\'un de discret qui sait se faire oublier pour capturer les vrais moments. C\'est exactement ce qu\'on a eu. Merci infiniment.', initials: 'MJ' },
      { name: 'Agence Volta', role: 'Directrice Artistique', text: 'Professionnalisme, réactivité, et un sens artistique rare. Un partenaire de confiance pour tous nos projets visuels. Nous recommandons vivement.', initials: 'AV' },
    ],
  },
  clients: {
    title: 'Ils nous font confiance',
  },
  contact: {
    title: 'Prenons contact',
    subtitle: 'Un projet ? Une idée ? Je suis à votre écoute.',
    address: '15 Rue Blatin',
    city: 'Clermont-Ferrand, France',
    email: 'contact@thenoctara.com',
    availability: 'Disponibilité',
    available: 'Disponible pour nouveaux projets',
    form: {
      name: 'Votre nom',
      email: 'Votre email',
      message: 'Votre message',
      send: 'Envoyer le message',
      sending: 'Envoi en cours...',
      success: 'Message envoyé ! Je vous répondrai sous 48h.',
    },
  },
  devis: {
    title: 'Demande de devis',
    subtitle: 'Parlez-moi de votre projet',
    fields: {
      company: 'Société (optionnel)',
      name: 'Votre nom *',
      email: 'Votre email *',
      date: 'Date souhaitée',
      location: 'Lieu / Ville',
      people: 'Nombre de personnes',
      budget: 'Budget estimé',
      message: 'Décrivez votre projet *',
      send: 'Envoyer la demande',
      sending: 'Envoi en cours...',
      success: 'Demande envoyée ! Je vous contacterai rapidement.',
    },
    budgets: ['< 500 €', '500 – 1 000 €', '1 000 – 2 000 €', '> 2 000 €'],
  },
  footer: {
    description: 'Photographe professionnel basé à Clermont-Ferrand. Chaque instant a une seule chance.',
    links: [
      { label: 'Portfolio', href: '#portfolio' },
      { label: 'À propos', href: '#about' },
      { label: 'Tarifs', href: '#tarifs' },
      { label: 'Avis', href: '#temoignages' },
      { label: 'Contact', href: '#contact' },
    ],
    legal: [
      { label: 'Confidentialité', href: '/confidentialite' },
      { label: 'CGV', href: '/cgv' },
      { label: 'Mentions légales', href: '/mentions-legales' },
    ],
    copyright: '© 2025 Noctara. Tous droits réservés.',
  },
}
